"use client"

import { useEffect, useId, useRef, useState } from "react"

/**
 * Renders a Mermaid diagram client-side. Mermaid is lazy-imported so its
 * ~400KB worth of JS only lands when a page actually needs a diagram.
 *
 * We initialize once, with a dark theme that matches our design tokens,
 * and then call `mermaid.render` per instance to get an SVG string. Each
 * render uses a stable id generated by `useId` to avoid collisions.
 */
export default function MermaidDiagram({
  chart,
  caption,
}: {
  chart: string
  caption?: string
}) {
  const rawId = useId()
  // Mermaid IDs must be valid CSS selectors (no colons, etc.).
  const id = "m" + rawId.replace(/[^a-zA-Z0-9]/g, "")
  const ref = useRef<HTMLDivElement>(null)
  const [svg, setSvg] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        const mermaid = (await import("mermaid")).default
        mermaid.initialize({
          startOnLoad: false,
          securityLevel: "strict",
          theme: "base",
          themeVariables: {
            background: "#141414",
            primaryColor: "#141414",
            primaryTextColor: "#F0F0F0",
            primaryBorderColor: "#1F1F1F",
            lineColor: "#8A8A8A",
            secondaryColor: "#1F1F1F",
            tertiaryColor: "#0D0D0D",
            // Accent for highlighted nodes
            mainBkg: "#141414",
            fontFamily: "var(--font-dm-mono), monospace",
            fontSize: "13px",
          },
        })
        const { svg } = await mermaid.render(id, chart)
        if (!cancelled) setSvg(svg)
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : String(err))
      }
    })()
    return () => {
      cancelled = true
    }
  }, [chart, id])

  return (
    <figure
      style={{
        margin: "2rem 0",
        padding: "1.5rem 1rem",
        border: "1px solid var(--color-border)",
        background: "var(--color-surface)",
        overflowX: "auto",
      }}
    >
      {error ? (
        <pre
          style={{
            fontFamily: "var(--font-dm-mono)",
            fontSize: "0.75rem",
            color: "#ff6b6b",
            whiteSpace: "pre-wrap",
          }}
        >
          mermaid error: {error}
        </pre>
      ) : svg ? (
        <div ref={ref} dangerouslySetInnerHTML={{ __html: svg }} style={{ display: "flex", justifyContent: "center" }} />
      ) : (
        <div
          style={{
            fontFamily: "var(--font-dm-mono)",
            fontSize: "0.7rem",
            color: "var(--color-muted)",
            textAlign: "center",
            padding: "1rem",
          }}
        >
          rendering diagram…
        </div>
      )}
      {caption && (
        <figcaption
          style={{
            marginTop: "0.75rem",
            fontFamily: "var(--font-dm-mono)",
            fontSize: "0.7rem",
            letterSpacing: "0.05em",
            color: "var(--color-muted)",
            textAlign: "center",
          }}
        >
          {caption}
        </figcaption>
      )}
    </figure>
  )
}
